"""Regenerate database/seed_characters.sql from data/characters.py:  python -m scripts.generate_seed_sql"""
import json
from pathlib import Path

from data.characters import CHARACTERS

q = lambda s: "'" + str(s).replace("'", "''") + "'"
out = ["-- Generated by scripts/generate_seed_sql.py — run AFTER schema.sql (idempotent).", ""]
for c in CHARACTERS:
    out.append(
        "insert into characters (id,name,series,attack,defense,tanking,speed,healing,intelligence,rarity,abilities,description) values "
        f"({q(c['id'])},{q(c['name'])},{q(c['series'])},{c['attack']},{c['defense']},{c['tanking']},{c['speed']},"
        f"{c['healing']},{c['intelligence']},{q(c['rarity'])},{q(json.dumps(c['abilities']))}::jsonb,{q(c['description'])}) "
        "on conflict (id) do update set name=excluded.name, series=excluded.series, attack=excluded.attack, "
        "defense=excluded.defense, tanking=excluded.tanking, speed=excluded.speed, healing=excluded.healing, "
        "intelligence=excluded.intelligence, rarity=excluded.rarity, abilities=excluded.abilities, "
        "description=excluded.description;")
out.append("")
for c in CHARACTERS:
    for cat in c["categories"]:
        out.append(f"insert into character_categories (character_id, category) values ({q(c['id'])},{q(cat)}) on conflict do nothing;")
Path(__file__).resolve().parent.parent.joinpath("database", "seed_characters.sql").write_text("\n".join(out) + "\n", encoding="utf-8")
print("wrote database/seed_characters.sql")
